#
# Copyright 2021 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Validate PubSub

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/new_quickstarts
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - feature/new_quickstarts
      - release-*
jobs:
  validate:
    name: Validate quickstart for `${{ matrix.quickstart_language }}` with `${{ matrix.quickstart_variant }}` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      DAPR_DEFAULT_IMAGE_REGISTRY: GHCR
      GOVER: 1.17
      KUBERNETES_VERSION: v1.21.1
      KIND_VERSION: v0.11.0
      KIND_IMAGE_SHA: sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest]
        quickstart_language: [go, csharp, javascript, python, java]
        quickstart_variant: [http, sdk]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Load environment variables
        uses: artursouza/export-env-action@v2
        with:
          envFile: './.github/env/global.env'
          expand: 'true'
      - name: Pinning Python to ${{ env.MACOS_PYTHON_VERSION }} on MacOS
        if: matrix.os == 'macos-latest' && matrix.quickstart_language == 'python'
        run: brew install python@${{ env.MACOS_PYTHON_VERSION }} && brew unlink python@${{ env.MACOS_PYTHON_VERSION }} && brew link --overwrite python@${{ env.MACOS_PYTHON_VERSION }}
      - name: Verify Python version
        if: matrix.quickstart_language == 'python'
        run: python3 --version
      - name: Upgrade pip and setuptools
        if: matrix.os == 'macos-latest' && matrix.quickstart_language == 'python'
        run: pip3 install --upgrade pip && python3 -m pip install --upgrade setuptools
      - name: Install podman - MacOS
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -rf `brew --cache`
          brew upgrade
          brew install podman
          which podman-mac-helper
          podman_helper=$(which podman-mac-helper)
          sudo ${podman_helper} install
          podman machine init
          podman machine start || echo "VM might not have started"
          sleep 10
          podman machine inspect
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Set up OpenJDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install .NET Core 
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            6.0.x
      - name: Set up Dapr CLI - Mac/Linux
        if: matrix.os != 'windows-latest'
        run: wget -q ${{ env.DAPR_INSTALL_URL }}/install.sh -O - | /bin/bash -s ${{ env.DAPR_CLI_VERSION }}
      - name: Set up Dapr CLI - Windows
        if: matrix.os == 'windows-latest'
        run: powershell -Command "\$$script=iwr -useb ${{ env.DAPR_INSTALL_URL }}/install.ps1; \$$block=[ScriptBlock]::Create(\$$script); invoke-command -ScriptBlock \$$block -ArgumentList ${{ env.DAPR_CLI_VERSION }}"     
      - name: Install Dapr
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          dapr init --runtime-version=${{ env.DAPR_RUNTIME_VERSION }} --container-runtime=podman
          dapr --version
      - name: Install utilities dependencies
        run: |
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          pip3 install setuptools wheel
          pip3 install mechanical-markdown
      - name: Validate ${{ matrix.quickstart_language }} ${{ matrix.quickstart_variant }} pubsub
        run: |
          pushd pub_sub/${{ matrix.quickstart_language }}/${{ matrix.quickstart_variant }}
          make validate
          popd
      - name: Linkcheck README.md
        run: |
          make validate